
name: test calculator

on:
 push:
  branches:
    - main
jobs:
  calculator:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      run: actions/checkout@v3
    - name: install node
      uses: actions/setup-node@v2
      with:
        node-version: "16.x"
    - name: install packages
      run: npm i
    - name: executing tests
      run: npm t
         